config/routes.rb
Rails.application.routes.draw do
  resources :events
  root "events#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ApplicationHelper

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    #meetup_api(params["event"]["city"])
    binding.pry
    fandango_api(90621)
    redirect_to root_path
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :zipcode)
  end

end

app/helpers/application_helper.rb
require 'uri'

module ApplicationHelper

  def meetup_api(city)
    params = { category: '1',
      city: city.split(' ').join('%20'),
      status: 'upcoming',
      format: 'json'
    }

    meetup_api = MeetupApi.new
    @events = meetup_api.open_events(params)
    #binding.pry
    @events['results'].each_with_index do |event, i|
      group_url_edited = @events['results'][i]['group']['urlname'].split(' ').join('-')
      group_url = "http://www.meetup.com/" + group_url_edited
      begin
        @event = Event.new(title: @events['results'][i]['name'], description: @events['results'][i]['description'], group_title: @events['results'][i]['group']['name'], event_url: @events['results'][i]['event_url'], group_url: group_url, latitude: @events['results'][i]['venue']['lat'], longitude: @events['results'][i]['venue']['lon'])
        @event.save
      rescue
        @event = Event.new(title: @events['results'][i]['name'], description: @events['results'][i]['description'], group_title: @events['results'][i]['group']['name'], event_url: @events['results'][i]['event_url'], group_url: group_url)
        @event.save
      end
    end
  end

  def fandango_api(zipcode)
    time = Time.now.to_i.to_s
    `curl http://api.fandango.com/v1/?op=theatersbypostalcodesearch&postalcode=` + zipcode.to_s + `&apikey=` + ENV['FANDANGO_KEY'].to_s + ENV['FANDANGO_SECRET'].to_s + Time.now.to_i.to_s
  end

end

app/views/events/index.html.erb
<h1>Whatever</h1>

<h2>Meetups</h2>
<ul>
  <% @events.each do |event| %>
    <li>
      <ul>
        <li><strong>Event Title: </strong><a href='/events/<%=event.id%>'><%= event.title %></a></li>
        <li><strong>Group Name: </strong><a href=<%= event.group_url%>><%= event.group_title %></a></li>
        <li><strong>Description: </strong><%= event.description %></li>
        <br><br>
      </ul>
    </li>
  <% end %>
</ul>

app/views/events/new.html.erb
<h1>Look for Meetups in your area</h1>

<%= form_for :event, url: events_path do |f| %>

  <div>
    <%= f.label :city, "City: " %>
    <%= f.text_area :city %>
  </div>

  <%= f.submit "Enter in events into db" %>

<% end %>

app/views/events/show.html.erb
<h1><strong>Event Title:</strong>
  <a href=<%=@event.event_url%>><%= @event.title %></a>
</h1>

<ul>
  <li>
    <strong>Group Title:</strong>
    <a href=<%=@event.group_url %>><%= @event.group_title %></a>
  </li>
  <li>
    <strong>Description:</strong>
      <%= @event.description %>
  </li>
</ul>
<%#= binding.pry %>
<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=<%=ENV['GOOGLE_MAPS_API_KEY']%>&q=<%= @event.latitude %>,<%= @event.longitude %>"></iframe>

<!-- <iframe width="300" height="170" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q='+YOUR_LAT+','+YOUR_LON+'&hl=es;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?q='+data.lat+','+data.lon+'&hl=es;z=14&amp;output=embed" style="color:#0000FF;text-align:left" target="_blank">See map bigger</a></small> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whatever</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= link_to "Home", root_path %>
    <%= link_to "New Meetups", new_event_path %>
  </header>
<%= yield %>

</body>
</html>